[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip esp32c6 --preverify --always-print-stacktrace"
rustflags = [
    "-C", "force-frame-pointers",
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "trace"
